#!/bin/sh
check=($(git merge HEAD))
echo "check merge branch"$check
response=$(git merge HEAD --all 2>&1 | grep "error:" || true)
echo "rESPONSE OUT IS.."$response
if [[ $check =~ "MERGE_HEAD exists" ]];then
  echo "Inside merge branch"
else
  echo "in else case"
fi
if [[ $response =~ "unmerged files" ]];then
  echo "Inside merge branch response"
fi