#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


DecompressExcel(){
java -cp ./target/classes ExcelHelper.ExcelDecompression
echo "In intellij precommit working Project level hook"
#java -cp ./target/classes ExcelHelper.XlsxtoCSV
git add .;
}

DecompressExcel



