#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".


DecompressExcel(){

runner=".m2/repository/com/ey/excelversioncontrol/1.0-SNAPSHOT/excelversioncontrol-1.0-SNAPSHOT.jar excelHelper.ExcelDecompression"

# Get the list of files staged for commit and check if it an excel
filesList=($(git diff --name-only --cached))

# If its an excel get the name of the file and pass a sourceFile Parameter to ExcelCompression method
for i in ${!filesList[@]}; do
  if [[ ${filesList[$i]} =~ \.xlsx$ ]];then
  	sourceFile=./${filesList[$i]}
	  destFolder=${sourceFile/.xlsx/DecompressedFolder}
  	echo "Source File Excel is $sourceFile"
	  echo "Dest folder is $destFolder"

	# Compile and run the ExcelDecompression
	  java -cp ~/$runner $sourceFile $destFolder
  fi
done
}

DecompressExcel



